name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Ensure report directory exists
        run: mkdir -p playwright-report

      - name: Start HTTP server
        run: |
          cd tests
          python -m http.server 8000 &  # Run in background
          cd ..

      - name: Run tests
        run: pytest --html=playwright-report/report.html --self-contained-html -v

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
